---
- name: Configure /boot/config.txt
  lineinfile:
    path: /boot/config.txt
    regexp: "^{{ item.key }}"
    insertafter: '[all]'
    line: "{{ item.key }}={{ item.value }}"
    state: present
  become: yes
  notify: reboot Raspberry Pi
  with_dict: 
    "start_x":            "1"
    "disable_camera_led": "1"
    "gpu_mem":            "128"